project:
  type: website
  output-dir: docs

website:
  title: "Julien Combes"
  navbar:
    right:
      - bio.qmd
      - about.qmd
      - icon: github
        href: https://github.com/JulienStats
    left:
      - text: Posts
        href: index.qmd
      - text: Research
        href: research.qmd
      - text: Publications
        href: publications.qmd
      - text: My Phd
        href: my_phd.qmd
      - text: Linux (FR)
        href: linux.qmd
        
format:
  html:
    respect-user-color-scheme: true
    code-tools: true
    theme:   
      light: flatly
      dark: darkly
    css: styles.css
    toc: true


bibliography: biblio.bib
execute:
  freeze: auto